# Generated by Django 3.1.2 on 2020-11-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_customer_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Nome', max_length=50),
            preserve_default=False,
        ),
    ]
